AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Parameters:
  UserTableName:
    Type: String
  UserEmailMappingIndexName:
    Type: String 
  ReviewsTableName:
    Type: String
  ReviewsByVoteIndexName:
    Type: String
  LatestReviewsTableName:
    Type: String
  GmailAddress:
    Type: String
  GamilClientID:
    Type: String
  GmailClientSecret:
    Type: String
  GmailRefreshToken:
    Type: String
Resources:
  DynamoDB:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./dynamodb/dynamodb.yaml
      Parameters:
        UserTableName: !Sub
          - ${AWS::StackName}-${DBName}
          - { DBName: !Ref UserTableName }
        UserEmailMappingIndexName: !Ref UserEmailMappingIndexName
        ReviewsTableName: !Sub
          - ${AWS::StackName}-${DBName}
          - { DBName: !Ref ReviewsTableName }
        LatestReviewsTableName: !Sub
          - ${AWS::StackName}-${DBName}
          - { DBName: !Ref LatestReviewsTableName }
        ReviewsByVoteIndexName: !Ref ReviewsByVoteIndexName
  Lambda:
    DependsOn:
      - DynamoDB
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./lambda/lambda.yaml
      Parameters:
        UserTableName: !Sub
          - ${AWS::StackName}-${DBName}
          - { DBName: !Ref UserTableName }
        UserEmailMappingIndexName: !Ref UserEmailMappingIndexName
        ReviewsTableName: !Sub
          - ${AWS::StackName}-${DBName}
          - { DBName: !Ref ReviewsTableName }
        ReviewsByVoteIndexName: !Ref ReviewsByVoteIndexName
        LatestReviewsTableName: !Sub
          - ${AWS::StackName}-${DBName}
          - { DBName: !Ref LatestReviewsTableName }
        UserDBArn: !GetAtt DynamoDB.Outputs.UserDBArn
        ReviewsDBArn: !GetAtt DynamoDB.Outputs.ReviewsDBArn
        LatestReviewsDBArn: !GetAtt DynamoDB.Outputs.LatestReviewsDBArn
        GmailAddress: !Ref GmailAddress
        GamilClientID: !Ref GamilClientID
        GmailClientSecret: !Ref GmailClientSecret
        GmailRefreshToken: !Ref GmailRefreshToken
        UserSNSTopic: !Ref UserSNSTopic
  UserSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: "User"
      DisplayName: "User"
