AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Parameters:
  ReviewsTableName:
    Type: String
  ReviewsByVoteIndexName:
    Type: String
  LatestReviewsTableName:
    Type: String
Resources:
  DynamoDB:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./dynamodb/dynamodb.yaml
      Parameters:
        ReviewsTableName: !Sub
          - ${AWS::StackName}-${DBName}
          - { DBName: !Ref ReviewsTableName }
        LatestReviewsTableName: !Sub
          - ${AWS::StackName}-${DBName}
          - { DBName: !Ref LatestReviewsTableName }
        ReviewsByVoteIndexName: !Ref ReviewsByVoteIndexName
  Lambda:
    DependsOn:
      - DynamoDB
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./lambda/lambda.yaml
      Parameters:
        ReviewsTableName: !Sub
          - ${AWS::StackName}-${DBName}
          - { DBName: !Ref ReviewsTableName }
        LatestReviewsTableName: !Sub
          - ${AWS::StackName}-${DBName}
          - { DBName: !Ref LatestReviewsTableName }
        ReviewsDBArn: !GetAtt DynamoDB.Outputs.ReviewsDBArn
        LatestReviewsDBArn: !GetAtt DynamoDB.Outputs.LatestReviewsDBArn
        ReviewsByVoteIndexName: !Ref ReviewsByVoteIndexName
