AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Parameters:
  ReviewsTableName:
    Type: String
Resources:
  DynamoDB:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./dynamodb/dynamodb.yaml
      Parameters:
        ReviewsTableName: !Sub
          - ${AWS::StackName}-${DBName}
          - { DBName: !Ref ReviewsTableName }
  Lambda:
    DependsOn:
      - DynamoDB
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./lambda/lambda.yaml
      Parameters:
        ReviewsTableName: !Sub
          - ${AWS::StackName}-${DBName}
          - { DBName: !Ref ReviewsTableName }
        ReviewsDBArn: !GetAtt DynamoDB.Outputs.ReviewsDBArn
