AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Resources:
  Lambda:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./lambda/lambda.yaml
      Parameters:
        UserSNSTopic: !Ref UserSNSTopic
  UserSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub ${AWS::StackName}-User
      DisplayName: "User"
