version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "plus-dev"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-66wc6266rpfl"
s3_prefix = "plus-dev"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
