AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Parameters:
  CoursesTableName:
    Type: String
Resources:
  CoursesHandler:
    Properties:
      CodeUri: ./courses
      Environment:
        Variables:
          CoursesTableName: !Ref CoursesTableName
      Handler: index.handler
      Events:
        HttpGet:
          Properties:
            Method: get
            Path: "/courses"
          Type: Api
      Handler: index.handler
      Role: !GetAtt "CoursesHandlerRole.Arn"
      Runtime: nodejs12.x
      Timeout: 5
    Type: AWS::Serverless::Function
  CoursesHandlerRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - "sts:AssumeRole"
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
        Version: "2012-10-17"
      Policies:
        - PolicyDocument:
            Statement:
              - Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Effect: Allow
                Resource:
                  - arn:aws:logs:*:*:*
            Version: "2012-10-17"
          PolicyName: LambdaPolicy
    Type: AWS::IAM::Role
