AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Parameters:
  ReviewsTableName:
    Type: String
  ReviewsDBArn:
    Type: String
Resources:
  GraphQL:
    Properties:
      CodeUri: ./graphql
      Handler: graphql.graphqlHandler
      Events:
        HttpGet:
          Properties:
            Method: get
            Path: /graphql
          Type: Api
        HttpPost:
          Properties:
            Method: post
            Path: /graphql
          Type: Api
      Environment:
        Variables:
          ReviewsTableName: !Ref ReviewsTableName
      Role: !GetAtt "GraphQLRole.Arn"
      Runtime: nodejs12.x
      Timeout: 20
    Type: AWS::Serverless::Function
  GraphQLRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - "sts:AssumeRole"
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
        Version: "2012-10-17"
      Policies:
        - PolicyDocument:
            Statement:
              - Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Effect: Allow
                Resource:
                  - arn:aws:logs:*:*:*
              - Action:
                  - dynamodb:PutItem
                  - dynamodb:Query
                Effect: Allow
                Resource:
                  - !Ref ReviewsDBArn
            Version: "2012-10-17"
          PolicyName: LambdaPolicy
    Type: AWS::IAM::Role
